name = "hkipo-api"
main = "src/index.js"
compatibility_date = "2024-01-01"

[[d1_databases]]
binding = "DB"
database_name = "hkipo-db"
database_id = "52e13838-0e66-4dae-a11b-3713187369ea"

[vars]
JWT_SECRET = "hkipo_jwt_secret_luweicao_2026_x7k9m2"
